In [1]:
# -*- coding: utf-8 -*-
from numpy import array, linalg
A = array([[ 2.0,  0.0, -1.0, -4.0,  0.0,  0.0],
           [ 2.0, -1.0,  0.0,  0.0,  4.0,  0.0],
           [ 0.0,  1.0,  1.0,  0.0,  0.0,  2.0],
           [ 1.0, -1.0, -1.0,  0.0,  0.0,  0.0],
           [-1.0,  0.0,  0.0,  0.0, -1.0,  1.0],
           [ 0.0,  0.0,  1.0,  1.0,  0.0, -1.0]])
# using linalg module
X = linalg.inv(A)
print("inverse of A=",X)


inverse of A= [[ 0.05263158 -0.15789474  0.42105263  0.57894737 -0.63157895  0.21052632]
 [-0.21052632 -0.36842105  0.31578947 -0.31578947 -1.47368421 -0.84210526]
 [ 0.26315789  0.21052632  0.10526316 -0.10526316  0.84210526  1.05263158]
 [-0.28947368 -0.13157895  0.18421053  0.31578947 -0.52631579 -0.15789474]
 [-0.07894737  0.23684211 -0.13157895 -0.36842105 -0.05263158 -0.31578947]
 [-0.02631579  0.07894737  0.28947368  0.21052632  0.31578947 -0.10526316]]
